# Generated by Django 6.0.5 on 2026-05-09 23:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria'), ('TI', 'Tarjeta de identidad'), ('PA', 'Pasaporte')], default='CC', max_length=3)),
                ('numero_identificacion', models.CharField(max_length=30, unique=True)),
                ('nombres', models.CharField(max_length=90)),
                ('apellidos', models.CharField(max_length=90)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=25)),
                ('cargo', models.CharField(max_length=90)),
                ('area', models.CharField(max_length=90)),
                ('eps', models.CharField(max_length=120, verbose_name='EPS')),
                ('arl', models.CharField(blank=True, max_length=120, verbose_name='ARL')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='TipoIncapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('entidad_responsable', models.CharField(choices=[('EPS', 'EPS'), ('ARL', 'ARL'), ('EMPRESA', 'Empresa')], max_length=20)),
                ('dias_maximos', models.PositiveIntegerField(default=180)),
                ('requiere_soporte', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de incapacidad',
                'verbose_name_plural': 'tipos de incapacidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=160)),
                ('detalle', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'auditoria',
                'verbose_name_plural': 'auditorias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Incapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_responsable', models.CharField(max_length=120)),
                ('numero_radicado', models.CharField(blank=True, max_length=60)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveIntegerField(default=1, editable=False)),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('TRANSCRITA', 'Transcrita'), ('COBRADA', 'Cobrada'), ('PAGADA', 'Pagada'), ('RECHAZADA', 'Rechazada')], default='RECIBIDA', max_length=20)),
                ('soporte_medico', models.FileField(blank=True, upload_to='soportes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incapacidades_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incapacidades', to='gestion.colaborador')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incapacidades_creadas', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incapacidades', to='gestion.tipoincapacidad')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('TRANSCRITA', 'Transcrita'), ('COBRADA', 'Cobrada'), ('PAGADA', 'Pagada'), ('RECHAZADA', 'Rechazada')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('TRANSCRITA', 'Transcrita'), ('COBRADA', 'Cobrada'), ('PAGADA', 'Pagada'), ('RECHAZADA', 'Rechazada')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incapacidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='gestion.incapacidad')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='incapacidad',
            index=models.Index(fields=['estado'], name='gestion_inc_estado_9a479f_idx'),
        ),
        migrations.AddIndex(
            model_name='incapacidad',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='gestion_inc_fecha_i_d9685c_idx'),
        ),
    ]
